version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["python", "server.py"]
    volumes:
      - .:/app
    environment:
      DB_HOST: ${DB_HOST}
    ports:
      - "5000:5000"
    devices:
      #- "/dev/video0:/dev/video0"